name: System Report

on: push

jobs:
  System-info:
    runs-on: ubuntu-latest
    steps:
      - name: System Report
        run: |
          uname -a
          df -h
          date
          sudo apt-get install tree
          tree -L 2 ~
  tool-check:
    runs-on: ubuntu-latest
    steps:
      - name: System Report
        run: |
          sudo apt-get install jq
          cat report.json
          python --version
          git -v