name: System Report

on: 
  push:
  workflow_dispatch:

jobs:

  system-info:
    runs-on: ubuntu-latest

    steps:
      - name: System Report
        run: |
          uname -s
          uname -r
          df -h
          date
          sudo apt-get update
          sudo apt-get install -y tree
          tree -L 2 ~


  tool-check:
    runs-on: ubuntu-latest

    steps:
      - name: Tool Check
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

          echo '{
            "os": "Ubuntu",
            "runner": "GitHub Actions",
            "status": "success"
          }' > report.json

          jq '.status' report.json

          python3 --version
          git --version
          jq --version

          echo "Report complete"