name: System Report

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: System Report
        run: |
          uname -a
          df -h
          date

  echo-goodbye: 
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "This step will fail"
          exit 0

      - name: Say goodbye
        run: echo "Goodbye, World!"